#:schema ./node_modules/wrangler/config-schema.json
name = "style-extractor"
compatibility_date = "2026-05-02"
pages_build_output_dir = "dist"

[vars]
PNPM_VERSION = "10.20.0"
NODE_VERSION = "22"
SKIP_DEPENDENCY_INSTALL = "true"
