import type { ThemePalette } from "./types";

// Re-export all constants from the main constants file
export {
	// Contrast boosting
	CONTRAST_BOOST_ENABLED,
	CONTRAST_BOOST_MAGNITUDE,
	CONTRAST_MIN_RATIO,
	CONTRAST_NUM_BACKGROUNDS,
	DANGER_HUE_RANGE_ORANGE_END,
	DANGER_HUE_RANGE_ORANGE_START,
	DANGER_HUE_RANGE_RED_END,
	DANGER_HUE_RANGE_RED_START,
	DELTA_E_DEDUP_THRESHOLD,
	// Delta E thresholds
	DELTA_E_SIMILAR,
	DESIGN_SYSTEM_CARBON_PATTERNS,
	DESIGN_SYSTEM_FLUENT_PATTERNS,
	// Design system detection
	DESIGN_SYSTEM_MATERIAL_PATTERNS,
	// Framework prefixes
	FRAMEWORK_PREFIXES,
	HUE_DIFF_LINK_VARIANT,
	// Hue thresholds
	HUE_DIFF_SIMILAR,
	HUE_DIFF_VERY_SIMILAR,
	LIGHTNESS_DIFF_LINK_VARIANT_MAX,
	// Lightness difference thresholds
	LIGHTNESS_DIFF_LINK_VARIANT_MIN,
	LIGHTNESS_THRESHOLD_BORDER_MAX,
	LIGHTNESS_THRESHOLD_BORDER_MIN,
	LIGHTNESS_THRESHOLD_DARK_TEXT,
	// Lightness thresholds
	LIGHTNESS_THRESHOLD_LIGHT_BG,
	LIGHTNESS_THRESHOLD_LIGHT_TEXT_PENALTY,
	LIGHTNESS_THRESHOLD_MUTED_MAX,
	LIGHTNESS_THRESHOLD_MUTED_MIN,
	LIGHTNESS_THRESHOLD_PRIMARY_MAX,
	LIGHTNESS_THRESHOLD_PRIMARY_MIN,
	LIGHTNESS_THRESHOLD_PRIMARY_VARIANT,
	// General settings
	MAX_RESULTS,
	// Alpha threshold
	MIN_ALPHA_THRESHOLD,
	MIN_SCORE,
	MODE_WEIGHT_DARK,
	// Mode weights
	MODE_WEIGHT_LIGHT,
	MODE_WEIGHT_NEUTRAL,
	MULTI_LEVEL_VAR_MAX_DEPTH,
	// Scoring
	PSEUDO_STATE_PENALTY,
	SATURATION_THRESHOLD_BORDER_ELIMINATION,
	// Saturation thresholds
	SATURATION_THRESHOLD_BORDER_GRAY,
	SATURATION_THRESHOLD_BORDER_MODERATE,
	SATURATION_THRESHOLD_BORDER_STRONG,
	SATURATION_THRESHOLD_DANGER,
	SATURATION_THRESHOLD_PRIMARY_VARIANT,
	SCORE_BOOST_BODY_BG,
	SCORE_BOOST_BODY_TEXT,
	SCORE_BOOST_BUTTON_PRIMARY,
	SCORE_BOOST_FOCUS_RING,
	SCORE_BOOST_GENERAL_BG,
	SCORE_BOOST_GOOD_GRAY_BORDER,
	SCORE_BOOST_HR_BORDER,
	SCORE_BOOST_INPUT_BORDER,
	SCORE_BOOST_LINK_PRIMARY,
	SCORE_BOOST_LINK_PSEUDO,
	SCORE_BOOST_LINK_VAR,
	SCORE_BOOST_PARAGRAPH_TEXT,
	SCORE_BOOST_PLAIN_ANCHOR,
	SCORE_FALLBACK_DANGER,
	SCORE_LINK_VARIANT_FALLBACK,
	SCORE_PENALTY_FRAMEWORK,
	SCORE_PENALTY_LIGHT_TEXT,
	SCORE_PENALTY_SATURATED_BORDER_MODERATE,
	SCORE_PENALTY_SATURATED_BORDER_STRONG,
	SCORE_PRIMARY_VARIANT_BASE,
	SCORE_PRIMARY_VARIANT_HUE_DIVISOR,
	SCORE_TOKEN_MATCH_BASE,
	// Semantic boost modifiers
	SEMANTIC_EXTRA_BOOST,
	SEMANTIC_EXTRA_BOOST_BG,
	SEMANTIC_EXTRA_BOOST_CARD,
	SEMANTIC_EXTRA_BOOST_SURFACE_VARIANT,
	SEMANTIC_VAR_BOOST,
	// Recursion limits
	VAR_RESOLUTION_MAX_DEPTH,
} from "../constants";

// Token matchers for semantic role detection
export const TOKEN_MATCHERS: Record<keyof ThemePalette, RegExp> = {
	background: /[-_]?(background|bg)[-_]?/i,
	surface: /[-_]?(card|panel|box|surface|container|modal|dialog)[-_]?/i,
	text: /[-_]?(text|foreground|fg|color)[-_]?/i,
	muted: /[-_]?(muted|caption|small|secondary|subtext)[-_]?/i,
	primary: /[-_]?(primary|brand|main|action)[-_]?/i,
	primaryVariant: /[-_]?primary[-_]?(container|variant)[-_]?/i,
	border: /[-_]?(border|divider|separator|line)[-_]?/i,
	danger: /[-_]?(danger|error|alert|destructive|invalid|dont)[-_]?/i,
	dangerVariant: /[-_]?(danger|error)[-_]?(container|variant)[-_]?/i,
	link: /[-_]?(link|anchor|hyperlink)[-_]?/i,
	linkVariant: /[-_]?link[-_]?(visited|hover|active)[-_]?/i,
	ring: /[-_]?(ring|outline|focus-ring)[-_]?/i,
};
